language: ruby
sudo: false
rvm:
  - 2.3.0 # Ruby most recent
# uncomment this line if your project needs to run something other than `rake`:

before_script:
  - psql -c 'create database orangelight_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake jetty:clean
  - bundle exec rake jetty:start
  - bundle exec rake pulsearch:index
  - RAILS_ENV=test bundle exec rake db:migrate
  - cp config/ip_whitelist.yml.tmpl config/ip_whitelist.yml
  - cp config/requests.yml.tmpl config/requests.yml

script: bundle exec rspec spec

branches:
  only:
    - development
notifications:
  email:
    recipients:
      - "tampakis@princeton.edu"
      - "jstroop@princeton.edu"
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"